### PR TITLE
Support CJK characters (Chinese, Japanese, Korean)

### PR DESCRIPTION
**Pull request by fand**
Almost all codes are from #16 .
I just added some test cases for coverages.

### CODE REVIEW

**Comment by fand** [comment]
Oh now I realized the coverage fall was not due to the characters......

**Comment by jamestalmage** [comment]
Is there a reason this is better than #16?

**Comment by fand** [comment]
Nope. I created this P-R because #16 seemed inactive for some reason such as Coveralls coverage fall.

**Comment by jamestalmage** [comment]
It was only inactive because GitHub doesn't notify you when someone fixes up your line comments in a PR. I will take a look at both later.

**Comment by fand** [comment]
Wait, I found another problem
We need to replace `foo.length` with `strlen` all around, like here:
https://github.com/fand/cli-table2/blob/master/src/utils.js#L172

**Comment by jamestalmage** [comment]
RE: `original-cli-table-index-tests`

The `original-*` files are there to show people this passes the entire test suite from the original `cli-table`.

That test should get moved.

**Comment by fand** [comment]
Moved tests to `table-test.js`.

**Comment by fand** [comment]
Now, this P-R includes 2 changes internally:

- `strlen` returns str's actual width on console (same as #16).
- `truncate` handles full-width characters correctly. 
  If the `str` cannot be shorten to `desiredLength`, it returns a string whose length is  `desiredLength - 1`.
  - `trunctate('漢字テスト', 6) === '漢字…'`
  - `trunctate('漢字テスト', 5) === '漢字…'`

**Comment by jamestalmage** [comment]
This is looking really good.

Can you add a few more tests with that make sure it works with CJK characters and colors?

- width is correct when both are used
- color continues on next line if softwraps are used
- ...?

**Comment by fand** [comment]
Added tests for `truncate`, `wordWrap`, `colorizeLines`!

**Comment by jamestalmage** [comment]
@fand - Awesome work! Thanks for your patience. Deployed as `0.2.0` PR.

**Comment by fand** [comment]
Thanks!!! @jamestalmage 
These codes are partly from #16, thank you! @LingyuCoder

**Pull request closed without merging**
